### ISSUE TITLE
Some PDF files crashes

### ISSUE THREAD

**Issue by tomswinkels** [JamesHeinrich/getID3#292]
With some PDF files the plugin crashes.

When i remove the '&' caracter in the getid3_pdf class the file works, but other files also work as well with the '&' character.

`$info = &$this->getid3->info;` to `$info = $this->getid3->info;`

See the attach file.
[formulier-taak-herexamen.pdf](https://github.com/JamesHeinrich/getID3/files/6048450/formulier-taak-herexamen.pdf)

**Comment by JamesHeinrich** [comment]
Fixed in https://github.com/JamesHeinrich/getID3/commit/80c557835768de3bb76e45878c18774ad522aafc

**Comment by tomswinkels** [comment]
@JamesHeinrich can you make a new release with that fix?

**Comment by zerocrates** [comment]
Even with this change I'm still seeing infinite looping on at least some PDFs. `ftell` seems to move all over the place so it's a higher level than just this inner loop, I guess.

**Comment by JamesHeinrich** [comment]
Do you have a non-sensitive PDF that shows this problem you can send me (info@getid3.org) for testing?

**Comment by zerocrates** [comment]
I'm checking with the user I got my example from; I'll pass it along if they give me a thumbs-up to send it.

**Comment by JamesHeinrich** [comment]
Thanks for the sample file, I can at least reproduce the infinite-loop behaviour. I may not be able to look at the issue for a couple days but I'll investigate what's causing the problem and let you know.

**Comment by JamesHeinrich** [comment]
So it turns out the PDF specification is a little more "flexible" (read: poorly standardized) than I had thought and the existing parsing code was not finding what it was looking for. I have rewritten that section and it should be a bit more robust now. 
https://github.com/JamesHeinrich/getID3/commit/a5f31b38c865ec6b0fc07041214e9d111a02775f
Please reopen this ticket if you find more PDFs that cause problems.
